### ISSUE TITLE
Problems with AutoLayout !

### ISSUE THREAD

**Issue by wonder2011** [CodeNationDev/UIMagicDropDown#3]
Hi, awesome work. I'm not using AutoLayout, i use right now PinLayout, but this pod is given me a loot of problems to become usable. When i set the autolayout this broke my own view layout. And, in the other hand, the list is ever displayer below, and never above of dropdown. Any idea how i can avoid autolayout here to make this work ?

**Comment by CodeNationDev** [comment]
Hey mate! thanks a lot! Did you try not using the bottom constraint? Is explained in the Readme, it's the only way for deploy the dropdown and avoid to pulldown all view below it.
