### ISSUE TITLE
Library crashing app 

### ISSUE THREAD

**Issue by PiotrBogus** [CodeNationDev/UIMagicDropDown#4]
Sometimes library isn't fast to load items before i try to set selected item.
You shouldn't force unwrap items
<img width="875" alt="Zrzut ekranu 2022-10-12 o 21 59 19" src="https://user-images.githubusercontent.com/36243625/195436494-4ee1386b-a33e-44aa-9fa4-bc5180d7c485.png">

**Comment by CodeNationDev** [comment]
You're in right, but this variable is initialised with a default value, may be an example of race condition. I will keep this in mind for change it... I never use the force unwrap, I don't know why I did that. Thanks dude!
